# == Class: php
#
# === Examples
#
#  class { 'php':
#    php     => 'NO',
#    php_fpm => 'YES',
#  }
#
# === Authors
#
# Aneesh C <aneeshchandrasekharan@gmail.com>
#

class php (
  $php                               = 'YES',
  $php_fpm                           = 'NO',
  $packagename_mod                   = $::php::params::packagename_mod,
  $package_name                      = $::php::params::package_name,
  $package_name_fpm                  = $::php::params::package_name_fpm,
  $configfile                        = $::php::params::configfile,
  $configfile_fpm                    = $::php::params::configfile_fpm,
  $template                          = 'php/configfile.erb',
  $engine                            = undef,
  $short_open_tag                    = undef,
  $asp_tags                          = undef,
  $precision                         = undef,
  $y2k_compliance                    = undef,
  $output_buffering                  = undef,
  $zlib_output_compression           = undef,
  $implicit_flush                    = undef,
  $unserialize_callback_func         = undef,
  $serialize_precision               = undef,
  $allow_call_time_pass_reference    = undef,
  $safe_mode                         = undef,
  $safe_mode_gid                     = undef,
  $safe_mode_include_dir             = undef,
  $safe_mode_exec_dir                = undef,
  $safe_mode_allowed_env_vars        = undef,
  $safe_mode_protected_env_vars      = undef,
  $open_basedir                      = undef,
  $disable_functions                 = undef,
  $disable_classes                   = undef,
  $zend_enable_gc                    = undef,
  $expose_php                        = undef,
  $max_execution_time                = undef,
  $max_input_time                    = undef,
  $memory_limit                      = undef,
  $error_reporting                   = undef,
  $display_errors                    = undef,
  $display_startup_errors            = undef,
  $log_errors                        = undef,
  $log_errors_max_len                = undef,
  $ignore_repeated_errors            = undef,
  $ignore_repeated_source            = undef,
  $report_memleaks                   = undef,
  $track_errors                      = undef,
  $html_errors                       = undef,
  $error_log                         = undef,
  $variables_order                   = undef,
  $request_order                     = undef,
  $register_globals                  = undef,
  $register_long_arrays              = undef,
  $register_argc_argv                = undef,
  $auto_globals_jit                  = undef,
  $post_max_size                     = undef,
  $magic_quotes_gpc                  = undef,
  $magic_quotes_runtime              = undef,
  $magic_quotes_sybase               = undef,
  $auto_prepend_file                 = undef,
  $auto_append_file                  = undef,
  $default_mimetype                  = undef,
  $default_charset                   = undef,
  $doc_root                          = undef,
  $user_dir                          = undef,
  $enable_dl                         = undef,
  $file_uploads                      = undef,
  $upload_tmp_dir                    = undef,
  $upload_max_filesize               = undef,
  $max_file_uploads                  = undef,
  $allow_url_fopen                   = undef,
  $allow_url_include                 = undef,
  $default_socket_timeout            = undef,
  $cli_server_color                  = undef,
  $pcre_jit                          = undef,
  $pdo_mysql_cache_size              = undef,
  $pdo_mysql_default_socket          = undef,
  $define_syslog_variables           = undef,
  $smtp                              = undef,
  $smtp_port                         = undef,
  $sendmail_path                     = undef,
  $mail_add_x_header                 = undef,
  $sql_safe_mode                     = undef,
  $odbc_allow_persistent             = undef,
  $odbc_check_persistent             = undef,
  $odbc_max_persistent               = undef,
  $odbc_max_links                    = undef,
  $odbc_defaultlrl                   = undef,
  $odbc_defaultbinmode               = undef,
  $ibase_allow_persistent            = undef,
  $ibase_max_persistent              = undef,
  $ibase_max_links                   = undef,
  $ibase_timestampformat             = undef,
  $ibase_dateformat                  = undef,
  $ibase_timeformat                  = undef,
  $mysql_allow_local_infile          = undef,
  $mysql_allow_persistent            = undef,
  $mysql_cache_size                  = undef,
  $mysql_max_persistent              = undef,
  $mysql_max_links                   = undef,
  $mysql_default_port                = undef,
  $mysql_default_socket              = undef,
  $mysql_default_host                = undef,
  $mysql_default_user                = undef,
  $mysql_default_password            = undef,
  $mysql_connect_timeout             = undef,
  $mysql_trace_mode                  = undef,
  $mysqli_max_persistent             = undef,
  $mysqli_allow_persistent           = undef,
  $mysqli_max_links                  = undef,
  $mysqli_cache_size                 = undef,
  $mysqli_default_port               = undef,
  $mysqli_default_socket             = undef,
  $mysqli_default_host               = undef,
  $mysqli_default_user               = undef,
  $mysqli_default_pw                 = undef,
  $mysqli_reconnect                  = undef,
  $mysqlnd_collect_statistics        = undef,
  $mysqlnd_collect_memory_statistics = undef,
  $pgsql_allow_persistent            = undef,
  $pgsql_auto_reset_persistent       = undef,
  $pgsql_max_persistent              = undef,
  $pgsql_max_links                   = undef,
  $pgsql_ignore_notice               = undef,
  $pgsql_log_notice                  = undef,
  $sybct_allow_persistent            = undef,
  $sybct_max_persistent              = undef,
  $sybct_max_links                   = undef,
  $sybct_min_server_severity         = undef,
  $sybct_min_client_severity         = undef,
  $bcmath_scale                      = undef,
  $session_save_handler              = undef,
  $session_use_strict_mode           = undef,
  $session_use_cookies               = undef,
  $session_use_only_cookies          = undef,
  $session_name                      = undef,
  $session_auto_start                = undef,
  $session_cookie_lifetime           = undef,
  $session_cookie_path               = undef,
  $session_cookie_domain             = undef,
  $session_cookie_httponly           = undef,
  $session_serialize_handler         = undef,
  $session_gc_probability            = undef,
  $session_gc_divisor                = undef,
  $session_gc_maxlifetime            = undef,
  $session_bug_compat_42             = undef,
  $session_bug_compat_warn           = undef,
  $session_referer_check             = undef,
  $session_entropy_length            = undef,
  $session_cache_limiter             = undef,
  $session_cache_expire              = undef,
  $session_use_trans_sid             = undef,
  $session_sid_length                = undef,
  $session_trans_sid_tags            = undef,
  $session_hash_function             = undef,
  $session_hash_bits_per_character   = undef,
  $session_sid_bits_per_character    = undef,
  $url_rewriter_tags                 = undef,
  $mssql_allow_persistent            = undef,
  $mssql_max_persistent              = undef,
  $mssql_max_links                   = undef,
  $mssql_min_error_severity          = undef,
  $mssql_min_message_severity        = undef,
  $mssql_compatibility_mode          = undef,
  $mssql_compatability_mode          = undef,
  $mssql_secure_connection           = undef,
  $zend_assertions                   = undef,
  $tidy_clean_output                 = undef,
  $soap_wsdl_cache_enabled           = undef,
  $soap_wsdl_cache_dir               = undef,
  $soap_wsdl_cache_ttl               = undef,
  $soap_wsdl_cache_limit             = undef,
  $ldap_max_links                    = undef,
) inherits ::php::params {
  package { $packagename_mod: ensure => installed }
  if $php == 'YES' {
    package { $package_name: ensure => installed }
    file { $configfile:
      require => package[$package_name],
      backup  => '.backup',
      content => template($template),
    }
  }
  if $php_fpm == 'YES' {
    package { $package_name_fpm: ensure => installed }
    if ! defined(File[$configfile_fpm]) {
      file { $configfile_fpm:
        require => package[$package_name_fpm],
        backup  => '.backup',
        content => template($template),
      }
    }
    if $::osfamily == 'RedHat' {
      service { 'php-fpm':
        require => package[$package_name_fpm],
        enable  => true,
      }
    }
  }
}
